import AuthProvider from './auth/Provider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div>layout</div>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
