// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js'
// }

'use client'

import { trpc } from '@/utils/trpc'

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>layout</div>
        {children}
      </body>
    </html>
  )
}

export default trpc.withTRPC(RootLayout)
